name: Deploy MasterPrintStrapi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: ${{ secrets.DEPLOY_PORT }}
          script: |
            # Navigate to project directory
            cd /home/print/masterPrintStrapi

            # Pull latest changes from Git
            git pull origin main

            # Install or update dependencies
            npm install

            # Increase memory for the build process
            export NODE_OPTIONS="--max-old-space-size=4096"

            # Build Strapi admin panel if needed
            npm run build

            # Add nvm-installed PM2 to PATH
            export PATH="/home/print/.nvm/versions/node/v18.20.7/bin:$PATH"

            # Restart or start the app with pm2 under the name print_dev
            pm2 restart print_dev || pm2 start npm --name print_dev -- start